### ISSUE TITLE
Documentation links

### ISSUE THREAD

**Issue by larsbrinkhoff** [nocrew/ostis#70]
Post links to interesting documentation here.

**Comment by larsbrinkhoff** [comment]
http://ataristeven.exxoshost.co.uk/txt/MMU.txt
http://ataristeven.exxoshost.co.uk/txt/GLUE.txt

**Comment by larsbrinkhoff** [comment]
http://dev-docs.atariforge.org/files/MC68901.pdf
http://dev-docs.atariforge.org/files/MC6850.pdf
http://dev-docs.atariforge.org/files/WD1772.pdf
http://dev-docs.atariforge.org/files/YM2149_1992.pdf
http://bitchin100.com/wiki/images/4/47/Hd6301.pdf

**Comment by larsbrinkhoff** [comment]
http://pasti.fxatari.com/68kdocs/AtariSTCycleCounting.html
http://pasti.fxatari.com/68kdocs/68kPrefetch.html

**Comment by larsbrinkhoff** [comment]
IKBD protocol:
http://dbug.kicks-ass.net/dbugforums/cgi-bin/yabb2/YaBB.pl?num=1280676369

**Comment by larsbrinkhoff** [comment]
http://www.atari-wiki.com/?title=ST_STE_Scanlines

**Comment by larsbrinkhoff** [comment]
http://alive.atari.org/

TODO: Links to individual articles.

**Comment by larsbrinkhoff** [comment]
http://github.com/DrCoolzic/AIR/tree/master/pasti
http://info-coach.fr/atari/documents/_mydoc/Pasti-documentation.pdf
http://www.sarnau.info/posts/2011/pasti_file_format/
http://atari.8bitchip.info/STXdesc.html

**Comment by larsbrinkhoff** [comment]
The *Atari Forum* is shock full of detailed information about the hardware components.  The problem is finding the gems.

Waveform timing diagram for GLUE/MMU/Shifter/display:
http://www.atari-forum.com/viewtopic.php?f=16&t=24855&start=363#p238041

**Comment by stefanberndtsson** [comment]
Put all this into a wiki page instead. Can this be closed in favour of Wiki?

https://github.com/nocrew/ostis/wiki/Documentation-links

**Comment by larsbrinkhoff** [comment]
Yep.
